# Generated by Django 3.0.3 on 2020-02-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=1024, verbose_name='Address1')),
                ('address2', models.CharField(max_length=1024, verbose_name='Address2')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('state', models.CharField(max_length=1024, verbose_name='State')),
                ('zip', models.CharField(max_length=1024, verbose_name='Zip')),
            ],
        ),
    ]
