# Generated by Django 3.0.3 on 2020-02-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1024, verbose_name='Name')),
                ('TaxID', models.CharField(max_length=1024, verbose_name='TaxID')),
                ('Phone', models.CharField(max_length=1024, verbose_name='Phone')),
                ('NAICS', models.CharField(max_length=1024, verbose_name='NAICS')),
                ('HasBeenProfitable', models.BooleanField(verbose_name='HasBeenProfitable')),
                ('HasBankruptedInLast7Years', models.BooleanField(verbose_name='HasBankruptedInLast7Years')),
                ('InceptionDate', models.DateTimeField(verbose_name='InceptionDate')),
            ],
        ),
        migrations.CreateModel(
            name='SelfReportedCashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnnualRevenue', models.FloatField(verbose_name='AnnualRevenue')),
                ('MonthlyAverageBankBalance', models.FloatField(verbose_name='MonthlyAverageBankBalance')),
                ('MonthlyAverageCreditCardVolume', models.FloatField(verbose_name='MonthlyAverageCreditCardVolume')),
            ],
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address1',
            new_name='Address1',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address2',
            new_name='Address2',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='city',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='state',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='zip',
            new_name='Zip',
        ),
    ]
