# Generated by Django 3.0.3 on 2020-02-11 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_auto_20200211_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFApplicationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestedLoanAmount', models.FloatField()),
                ('StatedCreditHistory', models.IntegerField()),
                ('LegalEntityType', models.CharField(max_length=1024)),
                ('FilterID', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='RequestHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CFRequestId', models.CharField(max_length=1024)),
                ('RequestDate', models.DateTimeField()),
                ('CFApiUserId', models.CharField(max_length=1024)),
                ('CFApiPassword', models.CharField(max_length=1024)),
                ('IsTestLead', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='Address1',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='address',
            name='Address2',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='address',
            name='City',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='address',
            name='State',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='address',
            name='Zip',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='business',
            name='HasBankruptedInLast7Years',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='HasBeenProfitable',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='InceptionDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='NAICS',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='business',
            name='Name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='business',
            name='Phone',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='business',
            name='TaxID',
            field=models.CharField(max_length=1024),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1024)),
                ('FirstName', models.CharField(max_length=1024)),
                ('LastName', models.CharField(max_length=1024)),
                ('Email', models.CharField(max_length=1024)),
                ('DateOfBirth', models.DateTimeField()),
                ('HomePhone', models.CharField(max_length=1024)),
                ('SSN', models.CharField(max_length=1024)),
                ('PercentageOfOwnership', models.FloatField()),
                ('HomeAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Business')),
                ('CFApplicationData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.CFApplicationData')),
                ('Owners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Owner')),
                ('RequestHeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.RequestHeader')),
            ],
        ),
    ]
