# Generated by Django 3.0.3 on 2020-02-11 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_auto_20200211_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restapp.Business'),
        ),
        migrations.AlterField(
            model_name='application',
            name='CFApplicationData',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restapp.CFApplicationData'),
        ),
        migrations.AlterField(
            model_name='application',
            name='RequestHeader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restapp.RequestHeader'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='HomeAddress',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restapp.Address'),
        ),
    ]
