# Generated by Django 3.0.3 on 2020-02-11 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0005_auto_20200211_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='Address',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='restapp.Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='SelfReportedCashFlow',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='restapp.SelfReportedCashFlow'),
            preserve_default=False,
        ),
    ]
